# Caution: use only the 'suggest_type' in case of using optuna
save_best: True
plot_agents: False
collect_stats: True

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
  run:
    dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  classname: bbrl.utils.logger.WandbLogger
  project: "lunarlander"
  group: "ddqn"
  tags: "manual"
  job_type: test
  log_dir: ${log_dir}
  cache_size: 10000
  every_n_seconds: 10
  verbose: False

gym_env:
  env_name: LunarLander-v2
  render_mode: rgb_array

algorithm:
  architecture:
    hidden_sizes: [512, 512]

  seed:
    train: 123
    eval: 999
    q: 123
    explorer: 456
    torch: 789

  explorer:
    epsilon_start: 0.7
    epsilon_end: 0.05
    decay: 0.996

  buffer:
    max_size: 50000
    batch_size: 500
    learning_starts: 4000

  target_critic_update_interval: 10000
  max_grad_norm: 1.9

  nb_evals: 10
  n_envs: 10
  n_steps_train: 64

  optim_n_updates: 10
  discount_factor: 0.99

  n_steps: 2000000
  eval_interval: 5000


optimizer:
  classname: torch.optim.Adam
  lr: 0.0005
