# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev14+g505487a.d20230809'
__version_tuple__ = version_tuple = (0, 1, 'dev14', 'g505487a.d20230809')
